export default {
  title: 'Voyage Voyage',
  artist: 'Dj Dark & Amélie',
  icon: '🌍',
  level: 'FR',
  file: 'voyage-voyage.mp3',
  // segundos a sumar a todos los start (ajuste global de sync)
  offset: 0,
  culture: {
    artist: 'Dúo rumano formado por el DJ Dj Dark y la cantante Amélie, conocidos por sus versiones dance de clásicos francófonos.',
    song: 'Cover de "Voyage Voyage", tema original de Desireless publicado en 1986.',
    language: 'Francés con vocabulario de viajes y geografía, estructura repetitiva ideal para practicar pronunciación.',
    funFacts: [
      'La canción original de Desireless fue un éxito europeo en 1986 y llegó a lo más alto de varias listas.',
      'Ha sido versionada por numerosos artistas, incluyendo Kate Ryan y Sirenia.'
    ]
  },
  
  subtitles: [
    { start: 0.0, duration: 4.0, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 4.0, duration: 4.5, original: "Au-dessus des vieux volcans", translation: "Por encima de los viejos volcanes" },
    { start: 8.5, duration: 4.5, original: "Glissent des ailes sous le tapis du vent", translation: "Se deslizan alas bajo la alfombra del viento" },
    { start: 13.0, duration: 3.0, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 16.0, duration: 4.0, original: "Éternellement", translation: "Eternamente" },
    { start: 20.5, duration: 4.5, original: "De nuages en marécages", translation: "De nubes en pantanos" },
    { start: 25.0, duration: 4.5, original: "De vent d'Espagne en pluie d'Équateur", translation: "Del viento de España a la lluvia del Ecuador" },
    { start: 29.5, duration: 3.0, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 32.5, duration: 4.0, original: "Vole dans les hauteurs", translation: "Vuela en las alturas" },
    { start: 37.0, duration: 3.5, original: "Au-dessus des capitales", translation: "Por encima de las capitales" },
    { start: 40.5, duration: 3.5, original: "Des idées fatales", translation: "De las ideas fatales" },
    { start: 44.0, duration: 4.0, original: "Regarde l'océan", translation: "Mira el océano" },
    { start: 48.5, duration: 3.5, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 52.0, duration: 4.5, original: "Plus loin que la nuit et le jour", translation: "Más lejos que la noche y el día" },
    { start: 56.5, duration: 3.5, original: "Voyage", translation: "Viaja" },
    { start: 60.0, duration: 4.5, original: "Dans l'espace inouï de l'amour", translation: "En el espacio inaudito del amor" },
    { start: 64.5, duration: 3.5, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 68.0, duration: 4.5, original: "Sur l'eau sacrée d'un fleuve indien", translation: "Sobre el agua sagrada de un río indio" },
    { start: 72.5, duration: 3.0, original: "Voyage", translation: "Viaja" },
    { start: 75.5, duration: 5.0, original: "Et jamais ne reviens", translation: "Y nunca vuelvas" },
    { start: 81.0, duration: 4.5, original: "Sur le Gange ou l'Amazone", translation: "Sobre el Ganges o el Amazonas" },
    { start: 85.5, duration: 4.5, original: "Chez les Blacks, chez les Sikhs, chez les Jaunes", translation: "Entre los negros, los sijs, los amarillos" },
    { start: 90.0, duration: 3.0, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 93.0, duration: 4.0, original: "Dans tout le royaume", translation: "Por todo el reino" },
    { start: 97.5, duration: 4.5, original: "Sur les dunes du Sahara", translation: "Sobre las dunas del Sahara" },
    { start: 102.0, duration: 4.5, original: "Des îles Fidji au Fujiyama", translation: "De las Islas Fidji al Fujiyama" },
    { start: 106.5, duration: 3.0, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 109.5, duration: 4.0, original: "Ne t'arrête pas", translation: "No te detengas" },
    { start: 114.0, duration: 3.5, original: "Au-dessus des barbelés", translation: "Por encima de las alambradas" },
    { start: 117.5, duration: 3.5, original: "Des cœurs bombardés", translation: "De los corazones bombardeados" },
    { start: 121.0, duration: 4.0, original: "Regarde l'océan", translation: "Mira el océano" },
    { start: 125.5, duration: 3.5, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 129.0, duration: 4.5, original: "Plus loin que la nuit et le jour", translation: "Más lejos que la noche y el día" },
    { start: 133.5, duration: 3.5, original: "Voyage", translation: "Viaja" },
    { start: 137.0, duration: 4.5, original: "Dans l'espace inouï de l'amour", translation: "En el espacio inaudito del amor" },
    { start: 141.5, duration: 3.5, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 145.0, duration: 4.5, original: "Sur l'eau sacrée d'un fleuve indien", translation: "Sobre el agua sagrada de un río indio" },
    { start: 149.5, duration: 3.0, original: "Voyage", translation: "Viaja" },
    { start: 152.5, duration: 5.0, original: "Et jamais ne reviens", translation: "Y nunca vuelvas" },
    { start: 158.5, duration: 3.5, original: "Au-dessus des capitales", translation: "Por encima de las capitales" },
    { start: 162.0, duration: 3.5, original: "Des idées fatales", translation: "De las ideas fatales" },
    { start: 165.5, duration: 4.0, original: "Regarde l'océan", translation: "Mira el océano" },
    { start: 170.0, duration: 3.5, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 173.5, duration: 4.5, original: "Plus loin que la nuit et le jour", translation: "Más lejos que la noche y el día" },
    { start: 178.0, duration: 3.5, original: "Voyage", translation: "Viaja" },
    { start: 181.5, duration: 4.5, original: "Dans l'espace inouï de l'amour", translation: "En el espacio inaudito del amor" },
    { start: 186.0, duration: 3.5, original: "Voyage, voyage", translation: "Viaja, viaja" },
    { start: 189.5, duration: 4.5, original: "Sur l'eau sacrée d'un fleuve indien", translation: "Sobre el agua sagrada de un río indio" },
    { start: 194.0, duration: 3.0, original: "Voyage", translation: "Viaja" },
    { start: 197.0, duration: 6.0, original: "Et jamais ne reviens", translation: "Y nunca vuelvas" },
  ]
};
