export default {
  title: 'Let It Be',
  artist: 'The Beatles',
  icon: '🕊️',
  level: 'B1',
  file: 'let_it_be.mp3',
  offset: 0,
  culture: {
    artist: 'The Beatles fueron una banda británica formada en Liverpool en 1960. Son considerados la banda más influyente de la historia de la música popular.',
    song: 'Let It Be (1970) fue escrita por Paul McCartney inspirada en un sueño con su madre Mary, quien había fallecido cuando él tenía 14 años. Es una de las últimas canciones grabadas antes de la separación de la banda.',
    language: 'Estructuras condicionales simples y vocabulario de consuelo. Mezcla presente simple con futuro (will). Expresiones como "let it be" (déjalo ser) y "words of wisdom" (palabras sabias). Nivel A2-B1.',
    funFacts: [
      'McCartney soñó que su madre le decía "Let it be" durante un periodo de tensiones en la banda.',
      'Fue la última canción de The Beatles en alcanzar el #1 en EE.UU.',
      'Billy Preston tocó el órgano en la grabación original.',
      'Existen dos versiones muy diferentes: la del single y la del álbum.'
    ]
  },

  subtitles: [
    { start: 13, duration: 3.5, original: "When I find myself in times of trouble", translation: "Cuando me encuentro en momentos difíciles" },
    { start: 16.4, duration: 2.5, original: "Mother Mary comes to me", translation: "La Madre María viene a mí" },
    { start: 19.9, duration: 2.0, original: "Speaking words of wisdom", translation: "Diciendo palabras sabias" },
    { start: 22, duration: 3.0, original: "Let it be", translation: "Déjalo ser" },
    { start: 25, duration: 3.5, original: "And in my hour of darkness", translation: "Y en mi hora de oscuridad" },
    { start: 28.3, duration: 3.5, original: "She is standing right in front of me", translation: "Ella está de pie justo frente a mí" },
    { start: 31.5, duration: 3.0, original: "Speaking words of wisdom", translation: "Diciendo palabras sabias" },
    { start: 35, duration: 2.5, original: "Let it be", translation: "Déjalo ser" },
    { start: 37.2, duration: 4.0, original: "Let it be, let it be", translation: "Déjalo ser, déjalo ser" },
    { start: 42.5, duration: 2.5, original: "Let it be, let it be", translation: "Déjalo ser, déjalo ser" },
    { start: 45, duration: 3.5, original: "Whisper words of wisdom", translation: "Susurra palabras sabias" },
    { start: 48.2, duration: 2.5, original: "Let it be", translation: "Déjalo ser" },
    { start: 51.9, duration: 5.5, original: "And when the broken-hearted people", translation: "Y cuando la gente con el corazón roto" },
    { start: 54.5, duration: 3.5, original: "Living in the world agree", translation: "Que vive en el mundo esté de acuerdo" },
    { start: 58, duration: 3.5, original: "There will be an answer", translation: "Habrá una respuesta" },
    { start: 61, duration: 3.0, original: "Let it be", translation: "Déjalo ser" },
    { start: 64.5, duration: 3.5, original: "For though they may be parted", translation: "Porque aunque estén separados" },
    { start: 67.5, duration: 3.5, original: "There is still a chance that they will see", translation: "Todavía hay una oportunidad de que vean" },
    { start: 71.5, duration: 3.0, original: "There will be an answer", translation: "Habrá una respuesta" },
    { start: 74, duration: 3.0, original: "Let it be", translation: "Déjalo ser" },
    { start: 77, duration: 5.0, original: "Let it be, let it be", translation: "Déjalo ser, déjalo ser" },
    { start: 82.4, duration: 2.5, original: "Let it be, let it be", translation: "Déjalo ser, déjalo ser" },
    { start: 84.8, duration: 4.0, original: "Yeah, there will be an answer", translation: "Sí, habrá una respuesta" },
    { start: 87.7, duration: 2.5, original: "Let it be", translation: "Déjalo ser" },
    { start: 158, duration: 4.5, original: "And when the night is cloudy", translation: "Y cuando la noche esté nublada" },
    { start: 163, duration: 4.5, original: "There is still a light that shines on me", translation: "Aún hay una luz que brilla sobre mí" },
    { start: 168, duration: 4.0, original: "Shine on until tomorrow", translation: "Brilla hasta mañana" },
    { start: 172, duration: 3.5, original: "Let it be", translation: "Déjalo ser" },
  ]
};
