export default {
  title: 'Stand By Me',
  artist: 'Ben E. King',
  icon: '🤝',
  level: 'A2',
  file: 'stand_by_me.mp3',
  offset: 0,
  culture: {
    artist: 'Cantante de soul y R&B (1938–2015), ex vocalista de The Drifters.',
    song: 'Inspirada en un espiritual gospel (1961). Una de las más versionadas del siglo XX.',
    language: 'Vocabulario emocional básico y condicionales simples — nivel A2.',
    funFacts: [
      'Compuesta en solo 15 minutos en el estudio.',
      'Su línea de bajo es de las más reconocidas del pop.'
    ]
  },
  subtitles: [
    { start: 15.0, duration: 4.0, original: "When the night has come", translation: "Cuando la noche ha llegado" },
    { start: 20.0, duration: 3.0, original: "And the land is dark", translation: "Y la tierra está oscura" },
    { start: 23.0, duration: 6.0, original: "And the moon is the only light we'll see", translation: "Y la luna es la única luz que veremos" },
    { start: 31.0, duration: 4.0, original: "No, I won't be afraid", translation: "No, no tendré miedo" },
    { start: 35.0, duration: 4.5, original: "Oh, I won't be afraid", translation: "Oh, no tendré miedo" },
    { start: 39.5, duration: 5.5, original: "Just as long as you stand, stand by me", translation: "Mientras tú estés, estés a mi lado" },
    { start: 45.5, duration: 2.5, original: "So darlin', darlin'", translation: "Así que cariño, cariño" },
    { start: 48.0, duration: 7.0, original: "Stand by me, oh stand by me", translation: "Quédate conmigo, oh quédate conmigo" },
    { start: 55.0, duration: 5.5, original: "Oh stand, stand by me", translation: "Oh quédate, quédate conmigo" },
    { start: 60.5, duration: 3.0, original: "Stand by me", translation: "Quédate conmigo" },
    { start: 63.5, duration: 4.0, original: "If the sky that we look upon", translation: "Si el cielo que miramos" },
    { start: 68.5, duration: 3.0, original: "Should tumble and fall", translation: "Se derrumbara y cayera" },
    { start: 71.5, duration: 5.5, original: "Or the mountains should crumble to the sea", translation: "O las montañas se desmoronaran al mar" },
    { start: 79.0, duration: 4.0, original: "I won't cry, I won't cry", translation: "No lloraré, no lloraré" },
    { start: 83.0, duration: 3.5, original: "No, I won't shed a tear", translation: "No, no derramaré una lágrima" },
    { start: 87.0, duration: 5.5, original: "Just as long as you stand, stand by me", translation: "Mientras tú estés, estés a mi lado" },
    { start: 92.5, duration: 3.5, original: "And darlin', darlin'", translation: "Y cariño, cariño" },
    { start: 96.0, duration: 6.5, original: "Stand by me, oh stand by me", translation: "Quédate conmigo, oh quédate conmigo" },
    { start: 102.5, duration: 5.5, original: "Oh stand now, stand by me", translation: "Oh quédate, quédate conmigo" },
    { start: 108.0, duration: 4.0, original: "Stand by me", translation: "Quédate conmigo" },
    { start: 143.0, duration: 1.5, original: "Darlin', darlin'", translation: "Cariño, cariño" },
    { start: 144.5, duration: 7.0, original: "Stand by me, oh stand by me", translation: "Quédate conmigo, oh quédate conmigo" },
    { start: 152.0, duration: 5.5, original: "Oh stand now, stand by me, stand by me", translation: "Oh quédate, quédate conmigo, quédate conmigo" },
    { start: 157.5, duration: 5.5, original: "Whenever you're in trouble, won't you stand by me", translation: "Siempre que estés en problemas, quédate conmigo" },
    { start: 163.0, duration: 7.0, original: "Oh stand by me, oh won't you stand now", translation: "Oh quédate conmigo, oh quédate ahora" },
    { start: 170.0, duration: 3.0, original: "Oh stand, stand by me", translation: "Quédate conmigo" },
  ]
};
