export default {
  title: 'Losing My Religion',
  artist: 'R.E.M.',
  icon: '🌀',
  level: 'C1',
  file: 'losing_my_religion.mp3',
  offset: 0,
  culture: {
    artist: 'R.E.M. fue una banda estadounidense de rock alternativo formada en 1980 en Athens, Georgia. Fueron pioneros del alternative rock y una influencia clave en el movimiento indie de los 90.',
    song: 'Losing My Religion (1991) es el mayor éxito comercial de R.E.M. El título es una expresión sureña que significa "perder la paciencia" o "estar al límite". La canción explora la vulnerabilidad, la obsesión no correspondida y la frustración de no poder comunicar lo que sientes.',
    language: 'Vocabulario idiomático avanzado: "losing my religion" (expresión regional), "the corner of my eye" (visión periférica), "slip" (deslizarse/escaparse). Estructuras condicionales complejas, metáforas sostenidas y registro poético que requiere inferencia cultural.',
    funFacts: [
      'El riff principal es de mandolina, no de guitarra — inusual para una canción de rock mainstream.',
      'Michael Stipe dijo que la canción trata sobre una obsesión no correspondida, no sobre religión.',
      'El video musical se inspiró en la iconografía de Caravaggio.',
      'Fue nominada a 6 Grammy y ganó dos premios MTV Video Music Awards.'
    ]
  },

  subtitles: [
    { start: 14, duration: 4.0, original: "Oh, life is bigger", translation: "Oh, la vida es más grande" },
    { start: 18, duration: 4.5, original: "It's bigger than you and you are not me", translation: "Es más grande que tú, y tú no eres yo" },
    { start: 23, duration: 5.0, original: "The lengths that I will go to", translation: "Las distancias a las que llegaré" },
    { start: 28, duration: 4.5, original: "The distance in your eyes", translation: "La distancia en tus ojos" },
    { start: 33, duration: 5.0, original: "Oh no, I've said too much", translation: "Oh no, he dicho demasiado" },
    { start: 38, duration: 4.0, original: "I set it up", translation: "Lo dejé en evidencia" },
    { start: 43, duration: 5.0, original: "That's me in the corner", translation: "Ese soy yo en la esquina" },
    { start: 48, duration: 5.0, original: "That's me in the spotlight", translation: "Ese soy yo bajo el reflector" },
    { start: 53, duration: 4.5, original: "Losing my religion", translation: "Perdiendo la paciencia" },
    { start: 58, duration: 5.5, original: "Trying to keep up with you", translation: "Intentando seguirte el paso" },
    { start: 64, duration: 5.0, original: "And I don't know if I can do it", translation: "Y no sé si puedo hacerlo" },
    { start: 69, duration: 5.5, original: "Oh no, I've said too much", translation: "Oh no, he dicho demasiado" },
    { start: 75, duration: 4.0, original: "I haven't said enough", translation: "No he dicho lo suficiente" },
    { start: 80, duration: 5.0, original: "I thought that I heard you laughing", translation: "Pensé que te oí riendo" },
    { start: 85, duration: 5.0, original: "I thought that I heard you sing", translation: "Pensé que te oí cantar" },
    { start: 90, duration: 5.5, original: "I think I thought I saw you try", translation: "Creo que pensé que te vi intentarlo" },
    { start: 96, duration: 5.0, original: "Every whisper of every waking hour", translation: "Cada susurro de cada hora despierta" },
    { start: 101, duration: 5.0, original: "I'm choosing my confessions", translation: "Estoy eligiendo mis confesiones" },
    { start: 106, duration: 5.5, original: "Trying to keep an eye on you", translation: "Intentando no perderte de vista" },
    { start: 112, duration: 5.0, original: "Like a hurt, lost and blinded fool", translation: "Como un tonto herido, perdido y cegado" },
    { start: 117, duration: 5.0, original: "Oh no, I've said too much", translation: "Oh no, he dicho demasiado" },
    { start: 122, duration: 4.0, original: "I set it up", translation: "Lo dejé en evidencia" },
    { start: 127, duration: 5.5, original: "Consider this the hint of the century", translation: "Considera esto la indirecta del siglo" },
    { start: 133, duration: 5.0, original: "Consider this the slip", translation: "Considera esto el desliz" },
    { start: 138, duration: 5.5, original: "That brought me to my knees, failed", translation: "Que me puso de rodillas, fracasado" },
    { start: 144, duration: 5.5, original: "What if all these fantasies come flailing around?", translation: "¿Qué pasa si todas estas fantasías se desmoronan?" },
    { start: 150, duration: 5.0, original: "Now I've said too much", translation: "Ahora he dicho demasiado" },
    { start: 156, duration: 5.5, original: "But I thought that I heard you laughing", translation: "Pero pensé que te oí riendo" },
    { start: 162, duration: 5.0, original: "I thought that I heard you sing", translation: "Pensé que te oí cantar" },
    { start: 167, duration: 5.5, original: "I think I thought I saw you try", translation: "Creo que pensé que te vi intentarlo" },
    { start: 173, duration: 5.5, original: "But that was just a dream", translation: "Pero eso fue solo un sueño" },
    { start: 179, duration: 5.0, original: "That was just a dream", translation: "Eso fue solo un sueño" },
  ]
};
