export default {
  title: 'Losing My Religion',
  artist: 'R.E.M.',
  icon: '🌀',
  level: 'B2',
  file: 'losing_my_religion.mp3',
  offset: 0,
  culture: {
    artist: 'Banda de alt-rock de Athens, Georgia (1980). Pioneros del indie de los 90.',
    song: 'Mayor éxito de R.E.M. (1991), sobre obsesión no correspondida.',
    language: 'Expresiones idiomáticas y registro poético accesible — nivel B2.',
    funFacts: [
      'El riff principal es de mandolina, no de guitarra.',
      'Nominada a 6 Grammy, ganó 2 MTV VMAs.'
    ]
  },

  subtitles: [
    { start: 14, duration: 4.0, original: "Oh, life is bigger", translation: "Oh, la vida es más grande" },
    { start: 18, duration: 4.5, original: "It's bigger than you and you are not me", translation: "Es más grande que tú, y tú no eres yo" },
    { start: 23, duration: 5.0, original: "The lengths that I will go to", translation: "Las distancias a las que llegaré" },
    { start: 28, duration: 4.5, original: "The distance in your eyes", translation: "La distancia en tus ojos" },
    { start: 33, duration: 5.0, original: "Oh no, I've said too much", translation: "Oh no, he dicho demasiado" },
    { start: 38, duration: 4.0, original: "I set it up", translation: "Lo dejé en evidencia" },
    { start: 43, duration: 5.0, original: "That's me in the corner", translation: "Ese soy yo en la esquina" },
    { start: 48, duration: 5.0, original: "That's me in the spotlight", translation: "Ese soy yo bajo el reflector" },
    { start: 53, duration: 4.5, original: "Losing my religion", translation: "Perdiendo la paciencia" },
    { start: 58, duration: 5.5, original: "Trying to keep up with you", translation: "Intentando seguirte el paso" },
    { start: 64, duration: 5.0, original: "And I don't know if I can do it", translation: "Y no sé si puedo hacerlo" },
    { start: 69, duration: 5.5, original: "Oh no, I've said too much", translation: "Oh no, he dicho demasiado" },
    { start: 75, duration: 4.0, original: "I haven't said enough", translation: "No he dicho lo suficiente" },
    { start: 80, duration: 5.0, original: "I thought that I heard you laughing", translation: "Pensé que te oí riendo" },
    { start: 85, duration: 5.0, original: "I thought that I heard you sing", translation: "Pensé que te oí cantar" },
    { start: 90, duration: 5.5, original: "I think I thought I saw you try", translation: "Creo que pensé que te vi intentarlo" },
    { start: 96, duration: 5.0, original: "Every whisper of every waking hour", translation: "Cada susurro de cada hora despierta" },
    { start: 101, duration: 5.0, original: "I'm choosing my confessions", translation: "Estoy eligiendo mis confesiones" },
    { start: 106, duration: 5.5, original: "Trying to keep an eye on you", translation: "Intentando no perderte de vista" },
    { start: 112, duration: 5.0, original: "Like a hurt, lost and blinded fool", translation: "Como un tonto herido, perdido y cegado" },
    { start: 117, duration: 5.0, original: "Oh no, I've said too much", translation: "Oh no, he dicho demasiado" },
    { start: 122, duration: 4.0, original: "I set it up", translation: "Lo dejé en evidencia" },
    { start: 127, duration: 5.5, original: "Consider this the hint of the century", translation: "Considera esto la indirecta del siglo" },
    { start: 133, duration: 5.0, original: "Consider this the slip", translation: "Considera esto el desliz" },
    { start: 138, duration: 5.5, original: "That brought me to my knees, failed", translation: "Que me puso de rodillas, fracasado" },
    { start: 144, duration: 5.5, original: "What if all these fantasies come flailing around?", translation: "¿Qué pasa si todas estas fantasías se desmoronan?" },
    { start: 150, duration: 5.0, original: "Now I've said too much", translation: "Ahora he dicho demasiado" },
    { start: 156, duration: 5.5, original: "But I thought that I heard you laughing", translation: "Pero pensé que te oí riendo" },
    { start: 162, duration: 5.0, original: "I thought that I heard you sing", translation: "Pensé que te oí cantar" },
    { start: 167, duration: 5.5, original: "I think I thought I saw you try", translation: "Creo que pensé que te vi intentarlo" },
    { start: 173, duration: 5.5, original: "But that was just a dream", translation: "Pero eso fue solo un sueño" },
    { start: 179, duration: 5.0, original: "That was just a dream", translation: "Eso fue solo un sueño" },
  ]
};
