export default {
  title: 'Dernière Danse',
  artist: 'Indila',
  icon: '🎤',
  level: 'FR',
  file: 'derniere-danse.mp3',
  // segundos a sumar a todos los start (ajuste global de sync)
  offset: 0,
  culture: {
    artist: 'Cantante francesa (Adila Sedraïa), de raíces multiculturales.',
    song: 'Single debut (2013), éxito masivo en Europa.',
    language: 'Francés poético pero accesible, con vocabulario emocional.',
    funFacts: [
      'El videoclip supera los 1.000 millones de views en YouTube.',
      'Su estilo vocal recuerda a Edith Piaf.'
    ]
  },
  subtitles: [
    // Letra
    { start: 1.0, duration: 3.5, original: "Ô ma douce souffrance", translation: "Oh, mi dulce sufrimiento" },
    { start: 4.5, duration: 4.0, original: "Pourquoi s'acharner ? Tu recommences", translation: "¿Por qué te empeñas? Tú lo vuelves a hacer" },
    { start: 8.5, duration: 4.0, original: "Je ne suis qu'un être sans importance", translation: "Solo soy un ser sin importancia" },
    { start: 12.5, duration: 3.0, original: "Sans lui, je suis un peu paro", translation: "Sin él, estoy un poco perdida" },
    { start: 15.5, duration: 3.0, original: "Je déambule seule dans le métro", translation: "Deambulo sola en el metro" },
    { start: 18.5, duration: 2.5, original: "Une dernière danse", translation: "Un último baile" },
    { start: 21.0, duration: 4.0, original: "Pour oublier ma peine immense", translation: "Para olvidar mi inmensa pena" },
    { start: 24.5, duration: 4.0, original: "Je veux m'enfuir, que tout recommence", translation: "Quiero huir, que todo vuelva a empezar" },
    { start: 29.0, duration: 5.0, original: "Ô ma douce souffrance", translation: "Oh, mi dulce sufrimiento" },
    { start: 35.0, duration: 5.0, original: "Je remue le ciel, le jour, la nuit", translation: "Muevo el cielo, el día, la noche" },
    { start: 40.0, duration: 4.5, original: "Je danse avec le vent, la pluie", translation: "Bailo con el viento, la lluvia" },
    { start: 44.0, duration: 4.0, original: "Un peu d'amour, un brin de miel", translation: "Un poco de amor, un poco de miel" },
    { start: 48.0, duration: 5.0, original: "Et je danse, danse, danse, danse, danse, danse, danse", translation: "Y bailo, bailo, bailo, bailo, bailo, bailo, bailo" },
    { start: 53.0, duration: 4.0, original: "Et dans le bruit, je cours et j'ai peur", translation: "Y en el ruido, corro y tengo miedo" },
    { start: 57.0, duration: 4.0, original: "Est-ce mon tour ? Vient la douleur", translation: "¿Es mi turno? Llega el dolor" },
    { start: 61.0, duration: 4.0, original: "Dans tout Paris, je m'abandonne", translation: "Por todo París, me abandono" },
    { start: 65.0, duration: 4.0, original: "Et je m'envole, vole, vole, vole, vole, vole, vole", translation: "Y vuelo, vuelo, vuelo, vuelo, vuelo, vuelo, vuelo" },
    { start: 69.0, duration: 2.5, original: "Que d'espérance", translation: "Cuánta esperanza" },
    { start: 71.5, duration: 4.0, original: "Sur ce chemin en ton absence", translation: "En este camino en tu ausencia" },
    { start: 75.5, duration: 3.5, original: "J'ai beau trimer, sans toi ma vie", translation: "Por más que me esfuerce, sin ti mi vida" },
    { start: 79.0, duration: 5.0, original: "N'est qu'un décor qui brille, vide de sens", translation: "No es más que un escenario que brilla, vacío de sentido" },
    { start: 86.0, duration: 4.0, original: "Je remue le ciel, le jour, la nuit", translation: "Muevo el cielo, el día, la noche" },
    { start: 90.0, duration: 4.0, original: "Je danse avec le vent, la pluie", translation: "Bailo con el viento, la lluvia" },
    { start: 94.0, duration: 4.0, original: "Un peu d'amour, un brin de miel", translation: "Un poco de amor, un poco de miel" },
    { start: 98.0, duration: 5.0, original: "Et je danse, danse, danse, danse, danse, danse, danse", translation: "Y bailo, bailo, bailo, bailo, bailo, bailo, bailo" },
    { start: 103.0, duration: 4.0, original: "Et dans le bruit, je cours et j'ai peur", translation: "Y en el ruido, corro y tengo miedo" },
    { start: 105.0, duration: 6.0, original: "Est-ce mon tour ? Vient la douleur", translation: "¿Es mi turno? Llega el dolor" },
    { start: 111.0, duration: 4.0, original: "Dans tout Paris, je m'abandonne", translation: "Por todo París, me abandono" },
    { start: 115.0, duration: 4.0, original: "Et je m'envole, vole, vole, vole, vole, vole, vole", translation: "Y vuelo, vuelo, vuelo, vuelo, vuelo, vuelo, vuelo" },
    { start: 135.0, duration: 4.0, original: "Dans cette douce souffrance", translation: "En este dulce sufrimiento" },
    { start: 139.0, duration: 4.0, original: "Dont j'ai payé toutes les offenses", translation: "Por el que pagué todas las ofensas" },
    { start: 143.0, duration: 4.0, original: "Écoute comme mon cœur est immense", translation: "Escucha, mi corazón es inmenso" },
    { start: 147.0, duration: 4.0, original: "Je suis une enfant du monde", translation: "Soy una niña del mundo" },
    { start: 153.0, duration: 4.0, original: "Je remue le ciel, le jour, la nuit", translation: "Muevo el cielo, el día, la noche" },
    { start: 157.0, duration: 4.0, original: "Je danse avec le vent, la pluie", translation: "Bailo con el viento, la lluvia" },
    { start: 161.0, duration: 4.0, original: "Un peu d'amour, un brin de miel", translation: "Un poco de amor, un poco de miel" },
    { start: 163.0, duration: 5.0, original: "Et je danse, danse, danse, danse, danse, danse, danse", translation: "Y bailo, bailo, bailo, bailo, bailo, bailo, bailo" },
    { start: 170.0, duration: 4.0, original: "Et dans le bruit, je cours et j'ai peur", translation: "Y en el ruido, corro y tengo miedo" },
    { start: 174.0, duration: 4.0, original: "Est-ce mon tour ? Vient la douleur", translation: "¿Es mi turno? Llega el dolor" },
    { start: 178.0, duration: 4.0, original: "Dans tout Paris, je m'abandonne", translation: "Por todo París, me abandono" },
    { start: 182.0, duration: 5.0, original: "Et je m'envole, vole, vole, vole, vole, vole, vole", translation: "Y vuelo, vuelo, vuelo, vuelo, vuelo, vuelo, vuelo" },
  ]
};
