export default {
  title: 'Dernière Danse',
  artist: 'Indila',
  icon: '🎤',
  file: 'derniere-danse.mp3',
  // segundos a sumar a todos los start (ajuste global de sync)
  offset: 0,
  culture: {
    artist: 'Indila es el nombre artístico de Adila Sedraïa, cantante francesa de raíces argelinas, egipcias, camboyanas e indias. Su estilo fusiona pop, chanson française y world music.',
    song: 'Dernière Danse (2013) fue su single debut y se convirtió en un éxito masivo en Europa. La canción habla de soledad, esperanza y resiliencia en las calles de París.',
    language: 'El francés de la canción es poético pero accesible. Usa vocabulario emocional (souffrance, espérance, douleur) y estructuras reflexivas (s\'acharner, m\'enfuir, m\'abandonne) muy comunes en el francés cotidiano.',
    funFacts: [
      'El videoclip acumula más de 1.000 millones de reproducciones en YouTube.',
      'Indila es muy reservada: rara vez da entrevistas o aparece en público.',
      'La canción se usa frecuentemente en clases de francés como lengua extranjera por su dicción clara.',
      'El estilo vocal recuerda a Edith Piaf, ícono de la chanson française.'
    ]
  },
  subtitles: [
    // Letra
    { start: 5, duration: 3.5, original: "Ô ma douce souffrance", translation: "Oh, mi dulce sufrimiento" },
    { start: 8.5, duration: 4.0, original: "Pourquoi s'acharner ? Tu recommences", translation: "¿Por qué te empeñas? Tú lo vuelves a hacer" },
    { start: 12.5, duration: 4.0, original: "Je ne suis qu'un être sans importance", translation: "Solo soy un ser sin importancia" },
    { start: 16.5, duration: 3.0, original: "Sans lui, je suis un peu paro", translation: "Sin él, estoy un poco perdida" },
    { start: 19.5, duration: 3.0, original: "Je déambule seule dans le métro", translation: "Deambulo sola en el metro" },
    { start: 22.5, duration: 2.5, original: "Une dernière danse", translation: "Un último baile" },
    { start: 25, duration: 4.0, original: "Pour oublier ma peine immense", translation: "Para olvidar mi inmensa pena" },
    { start: 28.5, duration: 4.0, original: "Je veux m'enfuir, que tout recommence", translation: "Quiero huir, que todo vuelva a empezar" },
    { start: 33, duration: 5.0, original: "Ô ma douce souffrance", translation: "Oh, mi dulce sufrimiento" },
    { start: 39, duration: 5.0, original: "Je remue le ciel, le jour, la nuit", translation: "Muevo el cielo, el día, la noche" },
    { start: 44, duration: 4.5, original: "Je danse avec le vent, la pluie", translation: "Bailo con el viento, la lluvia" },
    { start: 48, duration: 4.0, original: "Un peu d'amour, un brin de miel", translation: "Un poco de amor, un poco de miel" },
    { start: 52, duration: 5.0, original: "Et je danse, danse, danse, danse, danse, danse, danse", translation: "Y bailo, bailo, bailo, bailo, bailo, bailo, bailo" },
    { start: 57, duration: 4.0, original: "Et dans le bruit, je cours et j'ai peur", translation: "Y en el ruido, corro y tengo miedo" },
    { start: 61, duration: 4.0, original: "Est-ce mon tour ? Vient la douleur", translation: "¿Es mi turno? Llega el dolor" },
    { start: 65, duration: 4.0, original: "Dans tout Paris, je m'abandonne", translation: "Por todo París, me abandono" },
    { start: 69, duration: 4.0, original: "Et je m'envole, vole, vole, vole, vole, vole, vole", translation: "Y vuelo, vuelo, vuelo, vuelo, vuelo, vuelo, vuelo" },
    { start: 73, duration: 2.5, original: "Que d'espérance", translation: "Cuánta esperanza" },
    { start: 75.5, duration: 4.0, original: "Sur ce chemin en ton absence", translation: "En este camino en tu ausencia" },
    { start: 79.5, duration: 3.5, original: "J'ai beau trimer, sans toi ma vie", translation: "Por más que me esfuerce, sin ti mi vida" },
    { start: 83, duration: 5.0, original: "N'est qu'un décor qui brille, vide de sens", translation: "No es más que un escenario que brilla, vacío de sentido" },
    { start: 90, duration: 4.0, original: "Je remue le ciel, le jour, la nuit", translation: "Muevo el cielo, el día, la noche" },
    { start: 94, duration: 4.0, original: "Je danse avec le vent, la pluie", translation: "Bailo con el viento, la lluvia" },
    { start: 98, duration: 4.0, original: "Un peu d'amour, un brin de miel", translation: "Un poco de amor, un poco de miel" },
    { start: 102, duration: 5.0, original: "Et je danse, danse, danse, danse, danse, danse, danse", translation: "Y bailo, bailo, bailo, bailo, bailo, bailo, bailo" },
    { start: 107, duration: 4.0, original: "Et dans le bruit, je cours et j'ai peur", translation: "Y en el ruido, corro y tengo miedo" },
    { start: 109, duration: 6.0, original: "Est-ce mon tour ? Vient la douleur", translation: "¿Es mi turno? Llega el dolor" },
    { start: 115, duration: 4.0, original: "Dans tout Paris, je m'abandonne", translation: "Por todo París, me abandono" },
    { start: 119, duration: 4.0, original: "Et je m'envole, vole, vole, vole, vole, vole, vole", translation: "Y vuelo, vuelo, vuelo, vuelo, vuelo, vuelo, vuelo" },
    { start: 139, duration: 4.0, original: "Dans cette douce souffrance", translation: "En este dulce sufrimiento" },
    { start: 143, duration: 4.0, original: "Dont j'ai payé toutes les offenses", translation: "Por el que pagué todas las ofensas" },
    { start: 147, duration: 4.0, original: "Écoute comme mon cœur est immense", translation: "Escucha, mi corazón es inmenso" },
    { start: 151, duration: 4.0, original: "Je suis une enfant du monde", translation: "Soy una niña del mundo" },
    { start: 157, duration: 4.0, original: "Je remue le ciel, le jour, la nuit", translation: "Muevo el cielo, el día, la noche" },
    { start: 161, duration: 4.0, original: "Je danse avec le vent, la pluie", translation: "Bailo con el viento, la lluvia" },
    { start: 165, duration: 4.0, original: "Un peu d'amour, un brin de miel", translation: "Un poco de amor, un poco de miel" },
    { start: 167, duration: 5.0, original: "Et je danse, danse, danse, danse, danse, danse, danse", translation: "Y bailo, bailo, bailo, bailo, bailo, bailo, bailo" },
    { start: 174, duration: 4.0, original: "Et dans le bruit, je cours et j'ai peur", translation: "Y en el ruido, corro y tengo miedo" },
    { start: 178, duration: 4.0, original: "Est-ce mon tour ? Vient la douleur", translation: "¿Es mi turno? Llega el dolor" },
    { start: 182, duration: 4.0, original: "Dans tout Paris, je m'abandonne", translation: "Por todo París, me abandono" },
    { start: 186, duration: 5.0, original: "Et je m'envole, vole, vole, vole, vole, vole, vole", translation: "Y vuelo, vuelo, vuelo, vuelo, vuelo, vuelo, vuelo" },
  ]
};
