export default {
  title: 'Hello, Goodbye',
  artist: 'The Beatles',
  icon: '👋',
  level: 'A1',
  file: 'hello_goodbye.mp3',
  offset: 0,
  culture: {
    artist: 'The Beatles fueron una banda británica formada en Liverpool en 1960. Son considerados la banda más influyente de la historia de la música popular, con más de 600 millones de discos vendidos.',
    song: 'Hello, Goodbye (1967) fue escrita por Paul McCartney y lanzada como single del álbum Magical Mystery Tour. Es un juego de opuestos y contradicciones — un diálogo interno sobre la comunicación.',
    language: 'Vocabulario extremadamente simple: hello, goodbye, yes, no, stop, go. Usa opuestos básicos y estructuras repetitivas. Ideal para nivel A1 por la repetición y el vocabulario elemental.',
    funFacts: [
      'McCartney la escribió improvisando con opuestos mientras Alistair Taylor le hacía preguntas.',
      'Fue número 1 en el UK y en el US Billboard Hot 100.',
      'El video fue filmado en el Saville Theatre de Londres propiedad de Brian Epstein.',
      'John Lennon la consideraba una canción menor, pero fue un éxito comercial masivo.'
    ]
  },
  subtitles: [
    { start: 2, duration: 2.0, original: "I say no", translation: "Yo digo no" },
    { start: 4, duration: 7.0, original: "You say stop and I say go, go, go", translation: "Tú dices para y yo digo sigue, sigue, sigue" },
    { start: 13.5, duration: 1.5, original: "Oh no", translation: "Oh no" },
    { start: 17, duration: 4.5, original: "You say goodbye and I say hello", translation: "Tú dices adiós y yo digo hola" },
    { start: 22.5, duration: 2.5, original: "Hello, hello", translation: "Hola, hola" },
    { start: 25, duration: 2.5, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 27.5, duration: 3.5, original: "I say hello, hello hello", translation: "Yo digo hola, hola hola" },
    { start: 32.0, duration: 3.0, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 35.0, duration: 3.0, original: "I say hello", translation: "Yo digo hola" },
    { start: 38.0, duration: 4.0, original: "I say high, you say low", translation: "Yo digo alto, tú dices bajo" },
    { start: 43, duration: 5.0, original: "You say why and I say I don't know", translation: "Tú dices por qué y yo digo no sé" },
    { start: 52, duration: 2.0, original: "Oh no", translation: "Oh no" },
    { start: 55.0, duration: 4.5, original: "You say goodbye and I say hello", translation: "Tú dices adiós y yo digo hola" },
    { start: 60.5, duration: 2.5, original: "Hello, hello", translation: "Hola, hola" },
    { start: 63, duration: 3.0, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 66.0, duration: 3.0, original: "I say hello, hello hello", translation: "Yo digo hola, hola hola" },
    { start: 69.5, duration: 3.0, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 72.5, duration: 3.0, original: "I say hello", translation: "Yo digo hola" },
    { start: 79.5, duration: 2.5, original: "Why, why, why, why, why, why", translation: "¿Por qué, por qué, por qué?" },
    { start: 82.0, duration: 4.5, original: "Do you say goodbye?", translation: "¿Dices adiós?" },
    { start: 89, duration: 3.0, original: "Oh no", translation: "Oh no" },
    { start: 92, duration: 4.5, original: "You say goodbye and I say hello", translation: "Tú dices adiós y yo digo hola" },
    { start: 98, duration: 2.5, original: "Hello, hello", translation: "Hola, hola" },
    { start: 100.5, duration: 2.5, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 103, duration: 4.0, original: "I say hello, hello hello", translation: "Yo digo hola, hola hola" },
    { start: 107, duration: 3.0, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 110.0, duration: 2.5, original: "I say hello", translation: "Yo digo hola" },
    { start: 113.5, duration: 4.5, original: "You say yes, I say no", translation: "Tú dices sí, yo digo no" },
    { start: 118, duration: 5.5, original: "You say stop and I say go, go, go", translation: "Tú dices para y yo digo sigue, sigue, sigue" },
    { start: 125, duration: 2.5, original: "Oh, oh no", translation: "Oh, oh no" },
    { start: 129.5, duration: 4.5, original: "You say goodbye and I say hello", translation: "Tú dices adiós y yo digo hola" },
    { start: 134.5, duration: 3.0, original: "Hello, hello", translation: "Hola, hola" },
    { start: 137.5, duration: 2.5, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 140, duration: 4.5, original: "I say hello, hello", translation: "Yo digo hola, hola" },
  ]
};
