export default {
  title: 'Hello, Goodbye',
  artist: 'The Beatles',
  icon: '👋',
  level: 'A1',
  file: 'hello_goodbye.mp3',
  offset: 0,
  culture: {
    artist: 'Banda británica de Liverpool (1960), 600M+ discos vendidos.',
    song: 'Single de Magical Mystery Tour (1967), sobre opuestos y comunicación.',
    language: 'Vocabulario extremadamente simple — ideal A1.',
    funFacts: [
      'McCartney la improvisó jugando con opuestos.',
      '#1 en UK y en el US Billboard Hot 100.'
    ]
  },

  
  subtitles: [
    { start: 0.0, duration: 4.0, original: "You say yes, I say no", translation: "Tú dices sí, yo digo no" },
    { start: 4.0, duration: 7.0, original: "You say stop and I say go, go, go", translation: "Tú dices para y yo digo sigue, sigue, sigue" },
    { start: 13.5, duration: 1.5, original: "Oh no", translation: "Oh no" },
    { start: 17.0, duration: 4.5, original: "You say goodbye and I say hello", translation: "Tú dices adiós y yo digo hola" },
    { start: 22.5, duration: 2.5, original: "Hello, hello", translation: "Hola, hola" },
    { start: 25.0, duration: 2.7, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 27.7, duration: 3.7, original: "I say hello, hello hello", translation: "Yo digo hola, hola hola" },
    { start: 32.0, duration: 3.1, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 35.1, duration: 2.9, original: "I say hello", translation: "Yo digo hola" },
    { start: 38.0, duration: 5.0, original: "I say high, you say low", translation: "Yo digo alto, tú dices bajo" },
    { start: 43.0, duration: 7.0, original: "You say why and I say I don't know", translation: "Tú dices por qué y yo digo no sé" },
    { start: 52.0, duration: 2.0, original: "Oh no", translation: "Oh no" },
    { start: 55.0, duration: 5.5, original: "You say goodbye and I say hello", translation: "Tú dices adiós y yo digo hola" },
    { start: 60.5, duration: 2.5, original: "Hello, hello", translation: "Hola, hola" },
    { start: 63.0, duration: 3.0, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 66.0, duration: 3.0, original: "I say hello, hello hello", translation: "Yo digo hola, hola hola" },
    { start: 69.5, duration: 3.0, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 72.5, duration: 3.0, original: "I say hello", translation: "Yo digo hola" },
    { start: 79.5, duration: 2.5, original: "Why, why, why, why, why, why", translation: "¿Por qué, por qué, por qué?" },
    { start: 82.0, duration: 4.5, original: "Do you say goodbye?", translation: "¿Dices adiós?" },
    { start: 89.0, duration: 3.0, original: "Oh no", translation: "Oh no" },
    { start: 92.0, duration: 6.0, original: "You say goodbye and I say hello", translation: "Tú dices adiós y yo digo hola" },
    { start: 98.0, duration: 2.5, original: "Hello, hello", translation: "Hola, hola" },
    { start: 100.5, duration: 2.5, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 103.0, duration: 4.0, original: "I say hello, hello hello", translation: "Yo digo hola, hola hola" },
    { start: 107.0, duration: 3.0, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 110.0, duration: 2.5, original: "I say hello", translation: "Yo digo hola" },
    { start: 113.5, duration: 4.5, original: "You say yes, I say no", translation: "Tú dices sí, yo digo no" },
    { start: 118.0, duration: 7.0, original: "You say stop and I say go, go, go", translation: "Tú dices para y yo digo sigue, sigue, sigue" },
    { start: 125.0, duration: 4.5, original: "Oh, oh no", translation: "Oh, oh no" },
    { start: 129.5, duration: 5.0, original: "You say goodbye and I say hello", translation: "Tú dices adiós y yo digo hola" },
    { start: 134.5, duration: 3.0, original: "Hello, hello", translation: "Hola, hola" },
    { start: 137.5, duration: 2.5, original: "I don't know why you say goodbye", translation: "No sé por qué dices adiós" },
    { start: 140.0, duration: 4.5, original: "I say hello, hello", translation: "Yo digo hola, hola" },
  ]
};
