export default {
  title: 'Hotel California',
  artist: 'Eagles',
  icon: '🏨',
  level: 'B2',
  file: 'hotel_california.mp3',
  offset: 0,
  culture: {
    artist: 'Banda de rock de Los Ángeles (1971). Su Greatest Hits, entre los más vendidos de la historia.',
    song: 'Alegoría del exceso y el sueño americano (1977). Solo final legendario.',
    language: 'Vocabulario literario con imágenes sensoriales — nivel B1-B2.',
    funFacts: [
      'Felder compuso la música y la llamaba "Mexican Reggae".',
      '"You can never leave" es una de las frases más citadas del rock.'
    ]
  },

  
  subtitles: [
    { start: 1.0, duration: 4.0, original: "On a dark desert highway", translation: "En una oscura autopista del desierto" },
    { start: 5.0, duration: 3.0, original: "Cool wind in my hair", translation: "Viento fresco en mi cabello" },
    { start: 8.0, duration: 3.0, original: "Warm smell of colitas", translation: "Cálido olor a colitas" },
    { start: 11.0, duration: 3.0, original: "Rising up through the air", translation: "Subiendo por el aire" },
    { start: 14.5, duration: 3.0, original: "Up ahead in the distance", translation: "Más adelante a lo lejos" },
    { start: 17.5, duration: 3.0, original: "I saw a shimmering light", translation: "Vi una luz centelleante" },
    { start: 20.5, duration: 3.5, original: "My head grew heavy and my sight grew dim", translation: "Mi cabeza se hizo pesada y mi vista se nubló" },
    { start: 24.0, duration: 3.0, original: "I had to stop for the night", translation: "Tuve que parar por la noche" },
    { start: 27.0, duration: 3.0, original: "There she stood in the doorway", translation: "Ahí estaba ella en la entrada" },
    { start: 30.0, duration: 3.0, original: "I heard the mission bell", translation: "Oí la campana de la misión" },
    { start: 34.0, duration: 2.5, original: "And I was thinking to myself", translation: "Y estaba pensando para mí mismo" },
    { start: 36.5, duration: 4.0, original: "This could be heaven or this could be hell", translation: "Esto podría ser el cielo o el infierno" },
    { start: 40.5, duration: 3.5, original: "Then she lit up a candle", translation: "Entonces encendió una vela" },
    { start: 44.0, duration: 3.0, original: "And she showed me the way", translation: "Y me mostró el camino" },
    { start: 47.0, duration: 3.5, original: "There were voices down the corridor", translation: "Había voces al fondo del corredor" },
    { start: 50.5, duration: 3.0, original: "I thought I heard them say", translation: "Creí oírles decir" },
    { start: 53.5, duration: 5.0, original: "Welcome to the Hotel California", translation: "Bienvenido al Hotel California" },
    { start: 59.5, duration: 5.5, original: "Such a lovely place, such a lovely face", translation: "Un lugar tan encantador, un rostro tan encantador" },
    { start: 66.0, duration: 4.5, original: "Plenty of room at the Hotel California", translation: "Mucho espacio en el Hotel California" },
    { start: 71.5, duration: 6.0, original: "Any time of year, you can find it here", translation: "En cualquier época del año, puedes encontrarlo aquí" },
    { start: 79.5, duration: 3.0, original: "Her mind is Tiffany-twisted", translation: "Su mente está retorcida por Tiffany" },
    { start: 82.5, duration: 3.0, original: "She got the Mercedes-Benz", translation: "Ella tiene el Mercedes-Benz" },
    { start: 85.5, duration: 3.5, original: "She got a lot of pretty, pretty boys", translation: "Tiene muchos chicos bonitos, bonitos" },
    { start: 89.0, duration: 2.5, original: "That she calls friends", translation: "A los que llama amigos" },
    { start: 92.0, duration: 3.5, original: "How they dance in the courtyard", translation: "Cómo bailan en el patio" },
    { start: 95.5, duration: 2.5, original: "Sweet summer sweat", translation: "Dulce sudor de verano" },
    { start: 98.5, duration: 3.0, original: "Some dance to remember", translation: "Algunos bailan para recordar" },
    { start: 101.5, duration: 3.5, original: "Some dance to forget", translation: "Algunos bailan para olvidar" },
    { start: 104.5, duration: 3.5, original: "So I called up the captain", translation: "Así que llamé al capitán" },
    { start: 108.5, duration: 3.0, original: "Please bring me my wine", translation: "Por favor tráigame mi vino" },
    { start: 111.5, duration: 6.0, original: "He said, We haven't had that spirit here since 1969", translation: "Dijo: No hemos tenido ese espíritu aquí desde 1969" },
    { start: 117.5, duration: 7.0, original: "And still those voices are calling from far away", translation: "Y aún esas voces llaman desde lejos" },
    { start: 124.5, duration: 3.5, original: "Wake you up in the middle of the night", translation: "Te despiertan en medio de la noche" },
    { start: 128.0, duration: 3.5, original: "Just to hear them say", translation: "Solo para oírles decir" },
    { start: 131.5, duration: 5.0, original: "Welcome to the Hotel California", translation: "Bienvenido al Hotel California" },
    { start: 136.5, duration: 6.0, original: "Such a lovely place, such a lovely face", translation: "Un lugar tan encantador, un rostro tan encantador" },
    { start: 143.5, duration: 7.0, original: "They livin' it up at the Hotel California", translation: "Se la pasan en grande en el Hotel California" },
    { start: 150.5, duration: 7.5, original: "What a nice surprise, bring your alibis", translation: "Qué linda sorpresa, trae tus coartadas" },
    { start: 158.0, duration: 3.5, original: "Mirrors on the ceiling", translation: "Espejos en el techo" },
    { start: 161.5, duration: 3.0, original: "The pink champagne on ice, And she said", translation: "El champán rosado en hielo, Y ella dijo:" },
    { start: 164.5, duration: 6.0, original: "We are all just prisoners here, of our own device", translation: "Todos somos prisioneros aquí, de nuestro propio invento" },
    { start: 170.5, duration: 3.5, original: "And in the master's chambers", translation: "Y en las cámaras del amo" },
    { start: 174.0, duration: 3.0, original: "They gathered for the feast", translation: "Se reunieron para el festín" },
    { start: 177.0, duration: 3.0, original: "They stab it with their steely knives", translation: "Lo apuñalan con sus cuchillos de acero" },
    { start: 180.0, duration: 4.0, original: "But they just can't kill the beast", translation: "Pero simplemente no pueden matar a la bestia" },
    { start: 184.0, duration: 3.0, original: "Last thing I remember", translation: "Lo último que recuerdo" },
    { start: 187.0, duration: 4.0, original: "I was running for the door", translation: "Estaba corriendo hacia la puerta" },
    { start: 191.0, duration: 5.0, original: "I had to find the passage back to the place I was before", translation: "Tenía que encontrar el camino de regreso al lugar donde estaba antes" },
    { start: 196.0, duration: 3.5, original: "Relax, said the night man", translation: "Relájate, dijo el hombre de la noche" },
    { start: 199.5, duration: 3.5, original: "We are programmed to receive", translation: "Estamos programados para recibir" },
    { start: 203.0, duration: 4.0, original: "You can check out any time you like", translation: "Puedes marcharte cuando quieras" },
    { start: 207.0, duration: 4.0, original: "But you can never leave", translation: "Pero nunca podrás irte" },
  ]
};
