export default {
  title: 'Hotel California',
  artist: 'Eagles',
  icon: '🏨',
  level: 'B2',
  file: 'hotel_california.mp3',
  offset: 0,
  culture: {
    artist: 'Eagles es una banda estadounidense de rock formada en Los Ángeles en 1971. Su álbum "Their Greatest Hits" es uno de los más vendidos de todos los tiempos con más de 38 millones de copias solo en EE.UU.',
    song: 'Hotel California (1977) es una alegoría sobre el exceso, la autodestrucción y el lado oscuro del sueño americano. La guitarra final de 2 minutos es considerada uno de los mejores solos de la historia del rock.',
    language: 'Vocabulario rico y literario: metáforas, imágenes sensoriales (shimmering, colitas, twisted). Estructuras narrativas en pasado. Nivel B1-B2 por la complejidad léxica y las referencias culturales.',
    funFacts: [
      'Don Felder compuso la música en su casa y la llamaba "Mexican Reggae".',
      'La canción tardó meses en completarse — Henley y Frey reescribieron la letra múltiples veces.',
      'El famoso solo final fue grabado nota por nota, no improvisado.',
      '"You can check out any time you like, but you can never leave" es una de las frases más citadas del rock.'
    ]
  },

  subtitles: [
    { start: 52, duration: 4.5, original: "On a dark desert highway", translation: "En una oscura autopista del desierto" },
    { start: 57, duration: 3.5, original: "Cool wind in my hair", translation: "Viento fresco en mi cabello" },
    { start: 61, duration: 4.5, original: "Warm smell of colitas", translation: "Cálido olor a colitas" },
    { start: 66, duration: 4.0, original: "Rising up through the air", translation: "Subiendo por el aire" },
    { start: 71, duration: 4.5, original: "Up ahead in the distance", translation: "Más adelante a lo lejos" },
    { start: 76, duration: 4.0, original: "I saw a shimmering light", translation: "Vi una luz centelleante" },
    { start: 81, duration: 4.5, original: "My head grew heavy and my sight grew dim", translation: "Mi cabeza se hizo pesada y mi vista se nubló" },
    { start: 86, duration: 4.0, original: "I had to stop for the night", translation: "Tuve que parar por la noche" },
    { start: 91, duration: 4.5, original: "There she stood in the doorway", translation: "Ahí estaba ella en la entrada" },
    { start: 96, duration: 4.0, original: "I heard the mission bell", translation: "Oí la campana de la misión" },
    { start: 101, duration: 5.5, original: "And I was thinking to myself", translation: "Y estaba pensando para mí mismo" },
    { start: 107, duration: 5.0, original: "This could be heaven or this could be hell", translation: "Esto podría ser el cielo o el infierno" },
    { start: 113, duration: 4.5, original: "Then she lit up a candle", translation: "Entonces encendió una vela" },
    { start: 118, duration: 4.0, original: "And she showed me the way", translation: "Y me mostró el camino" },
    { start: 123, duration: 5.5, original: "There were voices down the corridor", translation: "Había voces al fondo del corredor" },
    { start: 129, duration: 4.5, original: "I thought I heard them say", translation: "Creí oírles decir" },
    { start: 134, duration: 5.0, original: "Welcome to the Hotel California", translation: "Bienvenido al Hotel California" },
    { start: 140, duration: 5.5, original: "Such a lovely place, such a lovely face", translation: "Un lugar tan encantador, un rostro tan encantador" },
    { start: 146, duration: 5.0, original: "Plenty of room at the Hotel California", translation: "Mucho espacio en el Hotel California" },
    { start: 152, duration: 5.5, original: "Any time of year, you can find it here", translation: "En cualquier época del año, puedes encontrarlo aquí" },
    { start: 158, duration: 5.0, original: "Her mind is Tiffany-twisted", translation: "Su mente está retorcida por Tiffany" },
    { start: 164, duration: 4.5, original: "She got the Mercedes-Benz", translation: "Ella tiene el Mercedes-Benz" },
    { start: 169, duration: 5.5, original: "She got a lot of pretty, pretty boys", translation: "Tiene muchos chicos bonitos, bonitos" },
    { start: 175, duration: 4.0, original: "That she calls friends", translation: "A los que llama amigos" },
    { start: 180, duration: 5.5, original: "Last thing I remember, I was running for the door", translation: "Lo último que recuerdo es que corría hacia la puerta" },
    { start: 186, duration: 5.5, original: "I had to find the passage back to the place I was before", translation: "Tenía que encontrar el pasaje de vuelta al lugar donde estaba antes" },
    { start: 192, duration: 5.0, original: "'Relax,' said the night man, 'we are programmed to receive'", translation: "'Relájate', dijo el vigilante nocturno, 'estamos programados para recibir'" },
    { start: 198, duration: 6.0, original: "You can check out any time you like, but you can never leave", translation: "Puedes irte cuando quieras, pero nunca podrás marcharte" },
  ]
};
