export default {
  title: 'Bohemian Rhapsody',
  artist: 'Queen',
  icon: '👑',
  file: 'bohemian_rhapsody.mp3',
  offset: 0,
  culture: {
    artist: 'Queen fue una banda británica de rock formada en 1970. Con Freddie Mercury como vocalista, son conocidos por su innovación musical, fusionando rock, ópera y pop progresivo.',
    song: 'Bohemian Rhapsody (1975) es una composición de 6 minutos que desafió todas las convenciones del pop. Tiene 6 secciones distintas: intro a capella, balada, solo de guitarra, ópera, hard rock y outro. Nunca fue tocada en vivo completa hasta mucho después.',
    language: 'Vocabulario variado y dramático: desde confesiones personales hasta referencias operísticas (Scaramouche, Bismillah, Beelzebub). Estructuras complejas con subjuntivos y condicionales. Nivel B2 por la diversidad léxica.',
    funFacts: [
      'Mercury la compuso durante varios años y la grabación tomó 3 semanas.',
      'Las harmonías vocales se sobregrabaron más de 180 veces.',
      'El video promocional es considerado uno de los primeros videoclips modernos.',
      'Volvió al #1 en 1991 tras la muerte de Mercury y otra vez en 2018 con la película biográfica.'
    ]
  },

  subtitles: [
    { start: 1, duration: 4.0, original: "Is this the real life?", translation: "¿Es esto la vida real?" },
    { start: 5, duration: 3.5, original: "Is this just fantasy?", translation: "¿Es esto solo fantasía?" },
    { start: 9, duration: 4.0, original: "Caught in a landslide", translation: "Atrapado en un derrumbe" },
    { start: 13, duration: 4.0, original: "No escape from reality", translation: "Sin escapatoria de la realidad" },
    { start: 18, duration: 3.5, original: "Open your eyes", translation: "Abre tus ojos" },
    { start: 22, duration: 4.5, original: "Look up to the skies and see", translation: "Mira hacia los cielos y observa" },
    { start: 27, duration: 4.0, original: "I'm just a poor boy, I need no sympathy", translation: "Solo soy un chico pobre, no necesito compasión" },
    { start: 32, duration: 5.0, original: "Because I'm easy come, easy go", translation: "Porque soy fácil de ir, fácil de venir" },
    { start: 38, duration: 3.5, original: "Little high, little low", translation: "Un poco alto, un poco bajo" },
    { start: 42, duration: 6.0, original: "Any way the wind blows doesn't really matter to me", translation: "De cualquier forma que sople el viento, no me importa realmente" },
    { start: 49, duration: 3.0, original: "To me", translation: "A mí" },
    { start: 53, duration: 4.5, original: "Mama, just killed a man", translation: "Mamá, acabo de matar a un hombre" },
    { start: 58, duration: 4.5, original: "Put a gun against his head", translation: "Le puse una pistola en la cabeza" },
    { start: 63, duration: 4.0, original: "Pulled my trigger, now he's dead", translation: "Apreté el gatillo, ahora está muerto" },
    { start: 68, duration: 5.0, original: "Mama, life had just begun", translation: "Mamá, la vida apenas había comenzado" },
    { start: 74, duration: 5.5, original: "But now I've gone and thrown it all away", translation: "Pero ahora fui y lo tiré todo por la borda" },
    { start: 80, duration: 5.0, original: "Mama, ooh, didn't mean to make you cry", translation: "Mamá, ooh, no quise hacerte llorar" },
    { start: 86, duration: 5.5, original: "If I'm not back again this time tomorrow", translation: "Si no he vuelto mañana a esta hora" },
    { start: 92, duration: 5.0, original: "Carry on, carry on as if nothing really matters", translation: "Continúa, continúa como si nada importara realmente" },
    { start: 98, duration: 4.0, original: "Too late, my time has come", translation: "Demasiado tarde, mi hora ha llegado" },
    { start: 103, duration: 5.0, original: "Sends shivers down my spine", translation: "Envía escalofríos por mi columna" },
    { start: 109, duration: 4.0, original: "Body's aching all the time", translation: "El cuerpo duele todo el tiempo" },
    { start: 114, duration: 5.5, original: "Goodbye, everybody, I've got to go", translation: "Adiós a todos, tengo que irme" },
    { start: 120, duration: 5.5, original: "Gotta leave you all behind and face the truth", translation: "Tengo que dejarlos a todos atrás y enfrentar la verdad" },
    { start: 126, duration: 5.0, original: "Mama, ooh, I don't wanna die", translation: "Mamá, ooh, no quiero morir" },
    { start: 132, duration: 6.0, original: "I sometimes wish I'd never been born at all", translation: "A veces desearía no haber nacido" },
    { start: 180, duration: 4.5, original: "So you think you can stone me and spit in my eye?", translation: "¿Así que crees que puedes apedrearme y escupirme en el ojo?" },
    { start: 185, duration: 5.0, original: "So you think you can love me and leave me to die?", translation: "¿Crees que puedes amarme y dejarme morir?" },
    { start: 191, duration: 4.0, original: "Oh, baby, can't do this to me, baby", translation: "Oh, nena, no puedes hacerme esto, nena" },
    { start: 196, duration: 5.0, original: "Just gotta get out, just gotta get right outta here", translation: "Solo tengo que salir, salir de aquí" },
    { start: 202, duration: 6.0, original: "Nothing really matters, anyone can see", translation: "Nada importa realmente, cualquiera puede ver" },
    { start: 209, duration: 5.0, original: "Nothing really matters to me", translation: "Nada importa realmente para mí" },
    { start: 215, duration: 5.0, original: "Any way the wind blows", translation: "De cualquier forma que sople el viento" },
  ]
};
