export default {
  title: 'Wonderwall',
  artist: 'Oasis',
  icon: '🧱',
  level: 'A2',
  file: 'wonderwall.mp3',
  offset: 0,
  culture: {
    artist: 'Oasis fue una banda británica de rock alternativo formada en Manchester en 1991 por los hermanos Gallagher. Son una de las bandas más exitosas del Britpop de los 90.',
    song: 'Wonderwall (1995) del álbum "(What\'s the Story) Morning Glory?" es una de las canciones más emblemáticas de los 90. Noel Gallagher la escribió pensando en su novia de entonces, Meg Mathews, aunque después dijo que trata sobre "un amigo imaginario que viene y te salva".',
    language: 'Vocabulario cotidiano con metáforas accesibles (road, light, wall). Estructuras condicionales ("by now you should\u2019ve somehow\u2026") y futuro con going to. Buen nivel A2 por repetición y vocabulario base.',
    funFacts: [
      'Es la canción más tocada en guitarra acústica en pubs y fiestas del mundo anglosajón.',
      'Noel la escribió completa en una noche mientras la banda estaba de gira.',
      'El término "wonderwall" viene de un álbum instrumental de George Harrison de 1968.',
      'Ha sido reproducida más de 1.6 mil millones de veces en Spotify.'
    ]
  },
  subtitles: [
    { start: 2.5, duration: 2.2, original: "Today is gonna be the day", translation: "Hoy va a ser el día" },
    { start: 4.7, duration: 2.8, original: "That they're gonna throw it back to you", translation: "En que te lo van a devolver" },
    { start: 7.5, duration: 2.7, original: "By now you should've somehow", translation: "A estas alturas ya deberías de algún modo" },
    { start: 10.2, duration: 2.8, original: "Realized what you gotta do", translation: "Haberte dado cuenta de lo que tienes que hacer" },
    { start: 13.0, duration: 2.8, original: "I don't believe that anybody", translation: "No creo que nadie" },
    { start: 15.8, duration: 3.7, original: "Feels the way I do about you now", translation: "Sienta lo que yo siento por ti ahora" },
    { start: 24.0, duration: 2.2, original: "Backbeat, the word is on the street", translation: "Ritmo, la voz corre por la calle" },
    { start: 26.2, duration: 2.8, original: "That the fire in your heart is out", translation: "Que el fuego en tu corazón se apagó" },
    { start: 29.0, duration: 2.4, original: "I'm sure you've heard it all before", translation: "Estoy seguro de que ya lo has oído todo antes" },
    { start: 31.5, duration: 2.5, original: "But you never really had a doubt", translation: "Pero nunca realmente tuviste una duda" },
    { start: 34.0, duration: 3.0, original: "I don't believe that anybody", translation: "No creo que nadie" },
    { start: 37.0, duration: 4.5, original: "Feels the way I do about you now", translation: "Sienta lo que yo siento por ti ahora" },
    { start: 44.0, duration: 5.0, original: "And all the roads we have to walk are winding", translation: "Y todos los caminos que tenemos que recorrer son sinuosos" },
    { start: 50.0, duration: 5.0, original: "And all the lights that lead us there are blinding", translation: "Y todas las luces que nos guían allí son cegadoras" },
    { start: 56.0, duration: 5.5, original: "There are many things that I would like to say to you", translation: "Hay muchas cosas que me gustaría decirte" },
    { start: 61.5, duration: 3.0, original: "But I don't know how", translation: "Pero no sé cómo" },
    { start: 67.0, duration: 2.5, original: "Because maybe", translation: "Porque tal vez" },
    { start: 72.0, duration: 3.5, original: "You're gonna be the one that saves me", translation: "Tú vas a ser quien me salve" },
    { start: 77.5, duration: 3.0, original: "And after all", translation: "Y después de todo" },
    { start: 82.5, duration: 4.0, original: "You're my wonderwall", translation: "Eres mi muro de maravillas" },
    { start: 95.0, duration: 2.4, original: "Today was gonna be the day", translation: "Hoy iba a ser el día" },
    { start: 97.4, duration: 3.3, original: "But they'll never throw it back to you", translation: "Pero nunca te lo van a devolver" },
    { start: 100.7, duration: 2.3, original: "By now you should've somehow", translation: "A estas alturas ya deberías de algún modo" },
    { start: 103.0, duration: 2.8, original: "Realized what you're not to do", translation: "Haberte dado cuenta de lo que no debes hacer" },
    { start: 105.8, duration: 2.7, original: "I don't believe that anybody", translation: "No creo que nadie" },
    { start: 108.5, duration: 3.5, original: "Feels the way I do about you now", translation: "Sienta lo que yo siento por ti ahora" },
  ]
};
